### PR TITLE
Make priority a property of Context

### PR DESCRIPTION
**Pull request by TimAbraldes**
This eliminates calls to `getPriority` and instead maintains a property
on Context objects that reflects the thread priority.

I ran the startup benchmark on two devices. 100 rounds, 25000ms delay, GC enabled.

Flame device

|         Test         | Baseline Mean |    Mean    |   +/-   |    %    |    P    |     Min    |     Max     | 
|:---------------------|--------------:|-----------:|--------:|--------:|--------:|-----------:|------------:|
| startupTime          |      16,598ms |   15,643ms |  -955ms |   -5.75 |  BETTER |   13,854ms |    18,816ms | 
| vmStartupTime        |       2,783ms |    2,606ms |  -177ms |   -6.37 |  BETTER |    2,160ms |     2,880ms | 
| bgStartupTime        |         897ms |      826ms |   -70ms |   -7.83 |  BETTER |      591ms |     1,026ms | 
| fgStartupTime        |      11,483ms |   10,775ms |  -708ms |   -6.16 |  BETTER |    9,630ms |    13,154ms | 
| fgRefreshStartupTime |       1,435ms |    1,436ms |     0ms |    0.02 |    SAME |      693ms |     2,698ms | 

Sony Xperia Z3

|         Test         | Baseline Mean |     Mean    |    +/-    |     %    |     P    |     Min     |     Max     | 
|:---------------------|--------------:|------------:|----------:|---------:|---------:|------------:|------------:|
| startupTime          |       8,883ms |     9,195ms |     312ms |     3.51 |    WORSE |     8,036ms |    10,147ms | 
| vmStartupTime        |       1,593ms |     1,609ms |      16ms |     1.02 |     SAME |     1,426ms |     1,819ms | 
| bgStartupTime        |         365ms |       376ms |      11ms |     3.11 |    WORSE |       329ms |       444ms | 
| fgStartupTime        |       6,434ms |     6,671ms |     238ms |     3.70 |    WORSE |     5,138ms |     7,550ms | 
| fgRefreshStartupTime |         491ms |       538ms |      47ms |     9.51 |    WORSE |       287ms |       948ms | 

I don't know whether to trust any of these numbers anymore, but if we can make performance better on slower devices it feels like we should go for it.

### CODE REVIEW

**Comment by mykmelez** [comment]
This one would be easier to validate via a micro-benchmark that exercises the scheduler. I don't know if there's an existing one that does that, but it should be relatively straightforward to write a basic benchmark for this, f.e. perhaps one that spins up a bunch of threads that each loop over a sleep call for some specified number of times.

**Comment by TimAbraldes** [comment]
I implemented a benchmark that starts up a bunch of threads and also tries to run an animation. After a couple of runs of the benchmark, it looks like this branch is maybe slightly better than master, but definitely within the margin of error.

Master run 1:
1.2:2.10 | In 15015ms, 863 frames were rendered for an FPS of 57 
1.2:7.5  | Thread med0 completed 7224 iterations 
1.2:17.5 | Thread hi3 completed 7257 iterations 
1.2:14.5 | Thread hi2 completed 7128 iterations 
1.2:10.5 | Thread med1 completed 6915 iterations 
1.2:8.5  | Thread hi0 completed 7203 iterations 
1.2:13.5 | Thread med2 completed 7075 iterations 
1.2:15.5 | Thread lo3 completed 7113 iterations 
1.2:12.5 | Thread lo2 completed 7127 iterations 
1.2:19.5 | Thread med4 completed 6970 iterations 
1.2:18.5 | Thread lo4 completed 6963 iterations 
1.2:11.5 | Thread hi1 completed 7171 iterations 
1.2:20.5 | Thread hi4 completed 7190 iterations 
1.2:16.5 | Thread med3 completed 7225 iterations 
1.2:9.5  | Thread lo1 completed 7216 iterations 
1.2:6.5  | Thread lo0 completed 7093 iterations 

Master run 2:
1.2:2.10 | In 15000ms, 865 frames were rendered for an FPS of 57 
1.2:11.5 | Thread hi1 completed 7059 iterations 
1.2:8.5  | Thread hi0 completed 7021 iterations 
1.2:7.5  | Thread med0 completed 6971 iterations 
1.2:17.5 | Thread hi3 completed 7041 iterations 
1.2:16.5 | Thread med3 completed 7069 iterations 
1.2:12.5 | Thread lo2 completed 6778 iterations 
1.2:10.5 | Thread med1 completed 7040 iterations 
1.2:6.5  | Thread lo0 completed 7081 iterations 
1.2:18.5 | Thread lo4 completed 6776 iterations 
1.2:9.5  | Thread lo1 completed 7020 iterations 
1.2:14.5 | Thread hi2 completed 6872 iterations 
1.2:19.5 | Thread med4 completed 6934 iterations 
1.2:15.5 | Thread lo3 completed 7026 iterations 
1.2:13.5 | Thread med2 completed 6844 iterations 
1.2:20.5 | Thread hi4 completed 6878 iterations 

Branch run 1:
1.2:2.10 | In 15004ms, 867 frames were rendered for an FPS of 57 
1.2:14.5 | Thread hi2 completed 7229 iterations 
1.2:11.5 | Thread hi1 completed 7301 iterations 
1.2:15.5 | Thread lo3 completed 7230 iterations 
1.2:16.5 | Thread med3 completed 7502 iterations 
1.2:9.5  | Thread lo1 completed 7497 iterations 
1.2:10.5 | Thread med1 completed 7089 iterations 
1.2:6.5  | Thread lo0 completed 7339 iterations 
1.2:17.5 | Thread hi3 completed 7483 iterations 
1.2:20.5 | Thread hi4 completed 7474 iterations 
1.2:8.5  | Thread hi0 completed 7443 iterations 
1.2:12.5 | Thread lo2 completed 7375 iterations 
1.2:18.5 | Thread lo4 completed 7510 iterations 
1.2:19.5 | Thread med4 completed 7499 iterations 
1.2:13.5 | Thread med2 completed 7517 iterations 
1.2:7.5  | Thread med0 completed 7462 iterations 

Branch run 2:
1.2:2.10 | In 15008ms, 864 frames were rendered for an FPS of 57 
1.2:20.5 | Thread hi4 completed 7099 iterations 
1.2:15.5 | Thread lo3 completed 7080 iterations 
1.2:13.5 | Thread med2 completed 7117 iterations 
1.2:16.5 | Thread med3 completed 6804 iterations 
1.2:9.5  | Thread lo1 completed 7133 iterations 
1.2:18.5 | Thread lo4 completed 7070 iterations 
1.2:14.5 | Thread hi2 completed 7047 iterations 
1.2:6.5  | Thread lo0 completed 7100 iterations 
1.2:8.5  | Thread hi0 completed 6956 iterations 
1.2:12.5 | Thread lo2 completed 6817 iterations 
1.2:7.5  | Thread med0 completed 7133 iterations 
1.2:11.5 | Thread hi1 completed 6959 iterations 
1.2:19.5 | Thread med4 completed 6945 iterations 
1.2:10.5 | Thread med1 completed 7007 iterations 
1.2:17.5 | Thread hi3 completed 7070 iterations 

The real insight gained from the benchmark, however, is that something is going haywire in our preemption: I had to add an explicit `Thread.sleep` call to make threads actually give up their execution time. Without the `sleep` call, a single thread was able to consume up to 30s of execution time without us ever switching to another thread, INCLUDING THE GUI THREAD! The result was that the whole application appeared to freeze for 30s and then show me this output:
1.2:20.5 | Thread hi4 completed 74214223 iterations 
1.2:19.5 | Thread med4 completed 1 iterations 
1.2:18.5 | Thread lo4 completed 1 iterations 
1.2:17.5 | Thread hi3 completed 1 iterations 
1.2:16.5 | Thread med3 completed 1 iterations 
1.2:15.5 | Thread lo3 completed 1 iterations 
1.2:14.5 | Thread hi2 completed 1 iterations 
1.2:13.5 | Thread med2 completed 1 iterations 
1.2:12.5 | Thread lo2 completed 1 iterations 
1.2:11.5 | Thread hi1 completed 1 iterations 
1.2:10.5 | Thread med1 completed 1 iterations 
1.2:9.5  | Thread lo1 completed 1 iterations 
1.2:8.5  | Thread hi0 completed 1 iterations 
1.2:7.5  | Thread med0 completed 1 iterations 
1.2:6.5  | Thread lo0 completed 1 iterations 
1.2:2.10 | In 30459ms, 1 frames were rendered for an FPS of 0

**Comment by TimAbraldes** [comment]
I think that all review comments are now addressed. Please let me know if there's further follow-up to do

**Comment by mykmelez** [comment]
Thanks for the benchmark! Despite the limited evidence of improvement, I think this is still worth taking, as it probably has a slight effect, and it's also a code simplification win.

**Pull request merged**
