### PR TITLE
WIP: Prevent ionmonkey inlining by adding try-catch in every compiled function

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by mykmelez** [comment]
@EricRahm Does the try/catch block actually need to surround the function body, or is it enough for there to be a try/catch in the body?

**Comment by mbebenita** [comment]
I think the `try/catch` can be anywhere in the method.

**Comment by mykmelez** [comment]
Ok, then it should be possible to do simply: `this.bodyEmitter.writeLn("try{}catch{}");`.

**Comment by mykmelez** [comment]
I'm marking this request as incomplete and closing it, as the work here appears to have stalled.  Please reopen the request if you resume work on it!

**Pull request closed without merging**
