### PR TITLE
WIP: Prevent ionmonkey compiling by adding try-finally in every compiled function

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:40.0) Gecko/40.0 Firefox/40.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|      Test     | Baseline Mean |    Mean   |   +/-   |   %   |    P   |    Min    |    Max    | 
|:--------------|--------------:|----------:|--------:|------:|-------:|----------:|----------:|
| startupTime   |      21,999ms |  21,392ms |  -607ms | -2.76 |   SAME |  19,479ms |  23,989ms | 
| vmStartupTime |       3,046ms |   3,038ms |    -8ms | -0.25 |   SAME |   2,914ms |   3,357ms | 
| bgStartupTime |       3,332ms |   3,411ms |    79ms |  2.38 |   SAME |   2,802ms |   4,180ms | 
| fgStartupTime |      15,621ms |  14,943ms |  -678ms | -4.34 | BETTER |  13,143ms |  17,912ms | 
| totalSize     |      27,908kb |  28,072kb |   164kb |  0.59 |   SAME |  25,320kb |  31,830kb | 
| domSize       |         113kb |     114kb |     1kb |  0.58 |   SAME |     111kb |     117kb | 
| styleSize     |         293kb |     293kb |     0kb |  0.01 |   SAME |     291kb |     295kb | 
| jsObjectsSize |      19,689kb |  19,665kb |   -25kb | -0.13 |   SAME |  18,456kb |  22,030kb | 
| jsStringsSize |         895kb |     894kb |    -1kb | -0.13 |   SAME |     854kb |     971kb | 
| jsOtherSize   |       6,464kb |   6,652kb |   188kb |  2.91 |   SAME |   4,529kb |   9,221kb | 
| otherSize     |         454kb |     455kb |     1kb |  0.22 |   SAME |     428kb |     500kb | 
| USS           |      60,822kb |  60,389kb |  -433kb | -0.71 |   SAME |  55,180kb |  74,844kb | 
| peakRSS       |     161,731kb | 164,654kb | 2,923kb |  1.81 |   SAME | 147,972kb | 167,220kb |

This is on Firefox OS 3.0.

**Comment by marco-c** [comment]
Using *b2g-info*, I noticed a peak of 143 MB on master and 104 MB on this branch.

**Comment by mykmelez** [comment]
> Using b2g-info, I noticed a peak of 143 MB on master and 104 MB on this branch.

Sold.

**Comment by marco-c** [comment]
The previous result is on 3.0, on 2.0 I can't see any difference...

**Comment by mykmelez** [comment]
> The previous result is on 3.0, on 2.0 I can't see any difference...

Are you testing on the same device?

**Comment by marco-c** [comment]
> Are you testing on the same device?

Yes, a Flame.

**Comment by mbebenita** [comment]
I suspect this will regress benchmarks. I think we should try to be a bit clever about when we do this, we could base our decision on Java method size and/or whether the method has loops or exception handlers.

**Comment by marco-c** [comment]
Yes, definitely, this is just to test whether disabling ionmonkey fixes USS peaks! In my testing it doesn't on 2.0, although I'd be more comfortable if someone else confirmed my findings.
If my findings were confirmed, we should file a platform bug about the 140 MB peak on 3.0.

This patch makes first run install faster for me, unsure why.

**Comment by mykmelez** [comment]
I'm marking this request as incomplete and closing it, as the work here appears to have stalled.  Please reopen the request if you resume work on it!

**Pull request closed without merging**
