### PR TITLE
Move Context-specific properties/functions into Context

### PR DESCRIPTION
**Pull request by TimAbraldes**
The global `U` and the `yield`, `pause`, and `stop` functions all belong in the `Context` class. This change makes other changes easier to write.

### CODE REVIEW

**Comment by TimAbraldes** [comment]
Tested on device, 30 rounds with 5s delay:

|         Test         | Baseline Mean |   Mean   |  +/-  |    %   |   P  |     Min    |     Max     | 
|:---------------------|--------------:|---------:|------:|-------:|-----:|-----------:|------------:|
| startupTime          |       9,999ms | 10,483ms | 484ms |   4.84 | SAME |    8,150ms |    16,621ms | 
| vmStartupTime        |       1,816ms |  1,802ms | -13ms |  -0.72 | SAME |    1,378ms |     2,309ms | 
| bgStartupTime        |         406ms |    425ms |  19ms |   4.64 | SAME |      361ms |       994ms | 
| fgStartupTime        |       7,170ms |  7,728ms | 558ms |   7.79 | SAME |    5,150ms |    13,390ms | 
| fgRefreshStartupTime |         607ms |    527ms | -80ms | -13.23 | SAME |      299ms |     1,163ms | 
| fgRestartTime        |           n/a |    NaNms |   n/a |    n/a |  n/a | Infinityms | -Infinityms |

**Comment by mykmelez** [comment]
This seems fine to me, provided it doesn't regress perf. And it doesn't appear to do so, at least on the startup benchmark, although I'm not sure how demonstrative that is.

@brendandahl Any concerns?

**Comment by marco-c** [comment]
To tell with more precision whether startup performance is affected, you could run the benchmark with more runs and enable GC between rounds (if you haven't already enabled it).

It could be interesting to run some of the benchmarks (under bench/) that yield often, for example the YieldBench.

**Comment by TimAbraldes** [comment]
Macbook Pro, 50 rounds, 50ms delay, GC enabled:

|         Test         | Baseline Mean |     Mean    |    +/-    |    %    |    P    |      Min     |      Max      | 
|:---------------------|--------------:|------------:|----------:|--------:|--------:|-------------:|--------------:|
| startupTime          |       2,010ms |     1,983ms |     -27ms |   -1.36 |    SAME |      1,839ms |       2,537ms | 
| vmStartupTime        |         236ms |       218ms |     -19ms |   -7.95 |    SAME |        205ms |         290ms | 
| bgStartupTime        |          45ms |        47ms |       2ms |    3.42 |   WORSE |         43ms |          67ms | 
| fgStartupTime        |       1,516ms |     1,509ms |      -7ms |   -0.43 |    SAME |      1,381ms |       1,925ms | 
| fgRefreshStartupTime |         213ms |       209ms |      -4ms |   -1.72 |    SAME |        192ms |         307ms | 

Sony Xperia Z3, 50 rounds, 50ms delay, GC enabled:

|         Test         | Baseline Mean |     Mean    |     +/-     |     %    |     P    |     Min     |     Max     | 
|:---------------------|--------------:|------------:|------------:|---------:|---------:|------------:|------------:|
| startupTime          |       8,712ms |     9,088ms |       376ms |     4.32 |    WORSE |     7,570ms |    10,296ms | 
| vmStartupTime        |       1,499ms |     1,468ms |       -30ms |    -2.03 |     SAME |     1,358ms |     1,667ms | 
| bgStartupTime        |         379ms |       389ms |        10ms |     2.63 |    WORSE |       350ms |       427ms | 
| fgStartupTime        |       6,345ms |     6,679ms |       334ms |     5.27 |    WORSE |     5,334ms |     7,622ms | 
| fgRefreshStartupTime |         490ms |       552ms |        62ms |    12.74 |    WORSE |       330ms |       900ms | 

Flame device, 50 rounds, 50ms delay, GC enabled:

|         Test         | Baseline Mean |    Mean    |    +/-   |    %    |     P    |     Min    |     Max     | 
|:---------------------|--------------:|-----------:|---------:|--------:|---------:|-----------:|------------:|
| startupTime          |      16,686ms |   17,187ms |    501ms |    3.00 |    WORSE |   15,033ms |    19,482ms | 
| vmStartupTime        |       2,490ms |    2,552ms |     62ms |    2.48 |    WORSE |    2,296ms |     2,796ms | 
| bgStartupTime        |         912ms |      931ms |     19ms |    2.08 |     SAME |      772ms |     1,092ms | 
| fgStartupTime        |      11,969ms |   12,474ms |    505ms |    4.22 |    WORSE |   10,638ms |    15,106ms | 
| fgRefreshStartupTime |       1,315ms |    1,231ms |    -84ms |   -6.41 |     SAME |      707ms |     2,445ms | 

Apparently this change by itself is actually a perf hit. Maybe I can rewrite the patches that rely on this one so that we don't need to make this change at all.

**Pull request closed without merging**
