### PR TITLE
update SpiderMonkey version for jsshell

### PR DESCRIPTION
**Pull request by mykmelez**
The version of SpiderMonkey we were using, 37.0b7, seems to have disappeared from ftp.mozilla.org. The latest release from the 37 branch is 37.0.2, so let's use that instead.

### CODE REVIEW

**Comment by marco-c** [comment]
What do you think about switching to a long term release so we don't have to do this too often?

**Comment by mykmelez** [comment]
> What do you think about switching to a long term release so we don't have to do this too often?

Seems fine to me.

**Comment by marco-c** [comment]
See https://github.com/mozilla/pluotsorbet/issues/1698#issuecomment-117861122 for the failure.

**Comment by mykmelez** [comment]
7a20255 uses 38.1.0esr, the most recent long term release. But it fails locally on the same test.

**Pull request merged**
