### PR TITLE
explicitly specify RC4 cipher for Python 2.7.10+ (fixes #1662)

### LINKED ISSUE #1662: Alert (2,40) exception in TestHttpsConnection, TestSSLStreamConnection
I just upgraded to a new Mac, and both javax.microedition.io.TestHttpsConnection and com.sun.midp.ssl.TestSSLStreamConnection are failing for me with `IOException: Alert (2,40)]`. Here's a stack from the TestHttpsConnection failure:

> javax.microedition.io.TestHttpsConnection-0: fail [length is > 0] main-all.js:780:5
> javax.microedition.io.TestHttpsConnection-1: fail [Unexpected exception: java.io.IOException: Alert (2,40)] main-all.js:780:5
> java.io.IOException: Alert (2,40) main-all.js:780:5
> java/io/IOException.<init>(Ljava/lang/String;)V, bci=0 main-all.js:780:5
> com/sun/midp/ssl/Record.rdRec(ZB)V, bci=0 main-all.js:780:5
> com/sun/midp/ssl/Handshake.getNextMsg(B)I, bci=0 main-all.js:780:5
> com/sun/midp/ssl/Handshake.rcvSrvrHello()I, bci=0 main-all.js:780:5
> com/sun/midp/ssl/Handshake.doHandShake(B)V, bci=0 main-all.js:780:5
> com/sun/midp/ssl/SSLStreamConnection.<init>(Ljava/lang/String;ILjava/io/InputStream;Ljava/io/OutputStream;Lcom/sun/midp/pki/CertStore;)V, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/https/Protocol.connect()Ljavax/microedition/io/StreamConnection;, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.streamConnect()V, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.startRequest()V, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest(ZZ)V, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest()V, bci=0 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.getResponseCode()I, bci=0 main-all.js:780:5
> javax/microedition/io/TestHttpsConnection.testBasicHttpsConnection()V, bci=0 main-all.js:780:5
> javax/microedition/io/TestHttpsConnection.test(Lgnu/testlet/TestHarness;)V, bci=0 main-all.js:780:5
> RunTestsMIDlet.runTest(Ljava/lang/String;)V, bci=0 main-all.js:780:5
> RunTestsMIDlet.startApp()V, bci=0 main-all.js:780:5
> javax/microedition/midlet/MIDletTunnelImpl.callStartApp(Ljavax/microedition/midlet/MIDlet;)V, bci=0 main-all.js:780:5
> com/sun/midp/midlet/MIDletPeer.startApp()V, bci=0 main-all.js:780:5
> com/sun/midp/midlet/MIDletStateHandler.startSuite(Lcom/sun/midp/midlet/MIDletSuiteExceptionListener;Lcom/sun/midp/midlet/MIDletSuite;ILjava/lang/String;)V, bci=0 main-all.js:780:5
> com/sun/midp/main/CldcMIDletSuiteLoader.startSuite()V, bci=0 main-all.js:780:5
> com/sun/midp/main/CldcMIDletSuiteLoader.runMIDletSuite()V, bci=0 main-all.js:780:5
> com/sun/midp/main/MIDletSuiteLoader.main([Ljava/lang/String;)V, bci=0 main-all.js:780:5
> com/sun/midp/ssl/Record.rdRec(ZB)V, bci=229 main-all.js:780:5
> com/sun/midp/ssl/Handshake.getNextMsg(B)I, bci=17 main-all.js:780:5
> com/sun/midp/ssl/Handshake.rcvSrvrHello()I, bci=5 main-all.js:780:5
> com/sun/midp/ssl/Handshake.doHandShake(B)V, bci=29 main-all.js:780:5
> com/sun/midp/ssl/SSLStreamConnection.<init>(Ljava/lang/String;ILjava/io/InputStream;Ljava/io/OutputStream;Lcom/sun/midp/pki/CertStore;)V, bci=173 main-all.js:780:5
> com/sun/midp/ssl/SSLStreamConnection.<init>(Ljava/lang/String;ILjava/io/InputStream;Ljava/io/OutputStream;Lcom/sun/midp/pki/CertStore;)V, bci=203 main-all.js:780:5
> com/sun/midp/io/j2me/https/Protocol.connect()Ljavax/microedition/io/StreamConnection;, bci=252 main-all.js:780:5
> com/sun/midp/io/j2me/https/Protocol.connect()Ljavax/microedition/io/StreamConnection;, bci=294 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.streamConnect()V, bci=60 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.startRequest()V, bci=12 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest(ZZ)V, bci=38 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest(ZZ)V, bci=68 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest(ZZ)V, bci=169 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.sendRequest()V, bci=6 main-all.js:780:5
> com/sun/midp/io/j2me/http/Protocol.getResponseCode()I, bci=8 main-all.js:780:5
> javax/microedition/io/TestHttpsConnection.testBasicHttpsConnection()V, bci=46 main-all.js:780:5
> javax/microedition/io/TestHttpsConnection.testBasicHttpsConnection()V, bci=245 main-all.js:780:5
> javax/microedition/io/TestHttpsConnection.test(Lgnu/testlet/TestHarness;)V, bci=9 main-all.js:780:5

(2,40) is FATAL, HNDSHK_FAIL per Record.java. @marco-c reported seeing this intermittently, but I'm seeing it consistently on the new Mac (although I never saw it on the old one). Perhaps it's a cert db issue.

I also note that Firefox has dropped support for SSLv3 (which the httpsServer.py and sslEchoServer.py test servers are both using), complaining "Firefox cannot guarantee the safety of your data on localhost:4443 because it uses SSLv3, a broken security protocol. Advanced info: ssl_error_unsupported_version".

### PR DESCRIPTION
**Pull request by mykmelez**
Python 2.7.10 removed *RC4* from the list of SSL ciphers, but *SSLStreamConnection* only supports *SSL_RSA_WITH_RC4_128_MD5* and *SSL_RSA_EXPORT_WITH_RC4_40_MD5*, so we have to specify it explicitly in order for that class to connect to the test servers.

This does "fix #1662" ;-), but it breaks loading pages from the test servers in Firefox, which reports "An error occurred during a connection to localhost:4443. Cannot communicate securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap)." So I'll probably have to expand this list, perhaps copying the default from Python (since I doesn't look like I can modify individual ciphers within it).

### CODE REVIEW

**Comment by mykmelez** [comment]
> This does "fix #1662" ;-), but it breaks loading pages from the test servers in Firefox, which reports "An error occurred during a connection to localhost:4443. Cannot communicate securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap)." So I'll probably have to expand this list, perhaps copying the default from Python (since I doesn't look like I can modify individual ciphers within it).

The latest commit does this.

**Comment by marco-c** [comment]
The tests are still failing for me with the *Alert (2,40)* message.

**Comment by mykmelez** [comment]
Hunh, interesting. Which OS, and which version of Python?

**Comment by marco-c** [comment]
Fedora 22, Python 2.7.10.

**Comment by marco-c** [comment]
I've tried setting `chipers='RC4'` as well, but it doesn't work anyway (I do see the error in Firefox, so it's actually using RC4).

**Comment by mykmelez** [comment]
> I've tried setting chipers='RC4' as well, but it doesn't work anyway (I do see the error in Firefox, so it's actually using RC4).

I set up a Fedora 22 VM and can reproduce. Bizarre. Not sure what's going on there.

**Comment by marco-c** [comment]
I'll merge this since it fixes the bug on Mac.

**Pull request merged**
