### PR TITLE
Set DEBUG_PRINT_ALL_EXCEPTIONS to true in non-release builds

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by brendandahl** [comment]
This makes it hard to filter out what are really exceptions.

**Comment by marco-c** [comment]
> This makes it hard to filter out what are really exceptions.

Yes, this is true, but it also gives more info when you're testing a MIDlet and hit a bug, which could be important in two cases:
 - A bug that you can't reproduce, so you can't simply run the MIDlet again modifying the property
 - A bug that a non-developer hits, who doesn't know how to build j2me.js

**Comment by mykmelez** [comment]
Can we parameterize this with a URL parameter instead? I.e. something like *printCaughtExceptions*. Then we can enable it without modifying source and independently from *release*.

**Comment by mykmelez** [comment]
I'm marking this request as incomplete and closing it, as the work here appears to have stalled. Please reopen the request if you resume work on it!

**Comment by marco-c** [comment]
Good idea, I've decided not to do this because it isn't as useful as I initially thought (people are not going to see these messages anyway).

**Pull request closed without merging**
