### PR TITLE
WIP: Make FS library directly use blobs

### PR DESCRIPTION
**Pull request by marco-c**
I've run the startup benchmark a few times:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:32.0) Gecko/32.0 Firefox/32.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|          Test         | Baseline Mean |   Mean   |    +/-   |    %   |       P       |    Min   |    Max   | 
|:----------------------|--------------:|---------:|---------:|-------:|--------------:|---------:|---------:|
| totalStartupTime      |      19,804ms | 22,970ms |  3,166ms |  15.99 |         WORSE | 18,273ms | 30,603ms | 
| vmStartupTime         |       3,182ms |  3,173ms |     -9ms |  -0.28 | INSIGNIFICANT |  2,882ms |  3,902ms | 
| backgroundStartupTime |       3,817ms |  3,481ms |   -336ms |  -8.81 |        BETTER |  2,390ms |  4,360ms | 
| foregroundStartupTime |      12,804ms | 16,316ms |  3,511ms |  27.42 |         WORSE | 11,255ms | 22,908ms | 
| totalSize             |      38,267kb | 38,552kb |    285kb |   0.74 | INSIGNIFICANT | 36,747kb | 40,590kb | 
| domSize               |         104kb |    103kb |     -1kb |  -0.82 |        BETTER |    100kb |    105kb | 
| styleSize             |         322kb |    324kb |      2kb |   0.68 |         WORSE |    321kb |    327kb | 
| jsObjectsSize         |      23,739kb | 19,837kb | -3,902kb | -16.44 |        BETTER | 18,929kb | 20,392kb | 
| jsStringsSize         |       2,043kb |  1,565kb |   -479kb | -23.43 |        BETTER |  1,449kb |  1,686kb | 
| jsOtherSize           |      11,578kb | 16,214kb |  4,637kb |  40.05 |         WORSE | 14,054kb | 17,722kb | 
| otherSize             |         481kb |    509kb |     28kb |   5.82 |         WORSE |    451kb |    553kb | 

There was another measurement on 32.0 that I forgot to copy. It showed worse startup time (insignificant), but with a smaller margin.

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:40.0) Gecko/40.0 Firefox/40.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|      Test     | Baseline Mean |   Mean   |    +/-   |    %   |    P   |    Min   |    Max   | 
|:--------------|--------------:|---------:|---------:|-------:|-------:|---------:|---------:|
| startupTime   |      22,464ms | 21,705ms |   -759ms |  -3.38 | BETTER | 19,873ms | 24,253ms | 
| vmStartupTime |       3,062ms |  3,080ms |     18ms |   0.59 |   SAME |  2,835ms |  3,385ms | 
| bgStartupTime |       3,538ms |  3,192ms |   -346ms |  -9.77 | BETTER |  2,389ms |  4,131ms | 
| fgStartupTime |      15,864ms | 15,432ms |   -431ms |  -2.72 |   SAME | 13,645ms | 17,847ms | 
| totalSize     |      28,036kb | 26,909kb | -1,127kb |  -4.02 | BETTER | 25,290kb | 28,531kb | 
| domSize       |         112kb |    110kb |     -2kb |  -1.34 | BETTER |    110kb |    111kb | 
| styleSize     |         293kb |    295kb |      2kb |   0.58 |  WORSE |    292kb |    297kb | 
| jsObjectsSize |      19,665kb | 19,053kb |   -612kb |  -3.11 | BETTER | 18,417kb | 19,182kb | 
| jsStringsSize |       1,059kb |    894kb |   -165kb | -15.55 | BETTER |    861kb |    969kb | 
| jsOtherSize   |       6,451kb |  6,071kb |   -380kb |  -5.89 |   SAME |  4,768kb |  7,485kb | 
| otherSize     |         457kb |    486kb |     29kb |   6.43 |  WORSE |    445kb |    530kb |

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:40.0) Gecko/40.0 Firefox/40.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|      Test     | Baseline Mean |    Mean   |    +/-    |    %   |    P   |    Min    |    Max    | 
|:--------------|--------------:|----------:|----------:|-------:|-------:|----------:|----------:|
| startupTime   |      21,799ms |  21,452ms |    -347ms |  -1.59 |   SAME |  19,788ms |  25,121ms | 
| vmStartupTime |       3,044ms |   3,039ms |      -5ms |  -0.17 |   SAME |   2,835ms |   3,377ms | 
| bgStartupTime |       3,175ms |   3,121ms |     -54ms |  -1.70 |   SAME |   2,396ms |   4,083ms | 
| fgStartupTime |      15,581ms |  15,293ms |    -288ms |  -1.85 |   SAME |  13,578ms |  18,105ms | 
| totalSize     |      27,976kb |  26,755kb |  -1,221kb |  -4.36 | BETTER |  25,554kb |  28,231kb | 
| domSize       |         112kb |     110kb |      -2kb |  -1.63 | BETTER |     110kb |     111kb | 
| styleSize     |         293kb |     295kb |       2kb |   0.71 |  WORSE |     293kb |     300kb | 
| jsObjectsSize |      19,889kb |  19,062kb |    -827kb |  -4.16 | BETTER |  18,425kb |  19,175kb | 
| jsStringsSize |         787kb |     854kb |      67kb |   8.49 |  WORSE |     832kb |     905kb | 
| jsOtherSize   |       6,437kb |   5,941kb |    -496kb |  -7.71 | BETTER |   4,760kb |   7,367kb | 
| otherSize     |         458kb |     493kb |      35kb |   7.69 |  WORSE |     459kb |     574kb | 
| USS           |      61,146kb |  59,057kb |  -2,090kb |  -3.42 |   SAME |  56,404kb |  65,848kb | 
| peakRSS       |     169,936kb | 141,759kb | -28,177kb | -16.58 | BETTER | 140,632kb | 141,984kb |

### CODE REVIEW

**Comment by marco-c** [comment]
|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:40.0) Gecko/40.0 Firefox/40.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|      Test     | Baseline Mean |    Mean   |    +/-    |    %   |    P   |    Min    |    Max    | 
|:--------------|--------------:|----------:|----------:|-------:|-------:|----------:|----------:|
| startupTime   |      21,659ms |  21,598ms |     -61ms |  -0.28 |   SAME |  19,610ms |  27,083ms | 
| vmStartupTime |       2,994ms |   2,977ms |     -17ms |  -0.57 |   SAME |   2,660ms |   3,339ms | 
| bgStartupTime |       3,201ms |   3,219ms |      18ms |   0.56 |   SAME |   2,393ms |   4,938ms | 
| fgStartupTime |      15,464ms |  15,402ms |     -62ms |  -0.40 |   SAME |  13,536ms |  18,805ms | 
| totalSize     |      28,008kb |  26,040kb |  -1,968kb |  -7.03 | BETTER |  25,085kb |  26,596kb | 
| domSize       |         113kb |     110kb |      -2kb |  -2.14 | BETTER |     110kb |     111kb | 
| styleSize     |         293kb |     295kb |       2kb |   0.66 |  WORSE |     293kb |     297kb | 
| jsObjectsSize |      19,823kb |  18,492kb |  -1,331kb |  -6.71 | BETTER |  18,433kb |  19,115kb | 
| jsStringsSize |         799kb |     943kb |     143kb |  17.92 |  WORSE |     923kb |     963kb | 
| jsOtherSize   |       6,524kb |   5,711kb |    -813kb | -12.46 | BETTER |   4,820kb |   6,281kb | 
| otherSize     |         456kb |     489kb |      33kb |   7.31 |  WORSE |     460kb |     533kb | 
| USS           |      60,481kb |  57,081kb |  -3,399kb |  -5.62 | BETTER |  55,216kb |  63,656kb | 
| peakRSS       |     164,544kb | 142,647kb | -21,897kb | -13.31 | BETTER | 141,348kb | 142,692kb |

**Comment by marco-c** [comment]
I've tested this with *b2g-procrank* on 2.0, my measurements confirm a > 20 MB decrease in peak memory usage (from ~100 MB to ~80 MB).
USS in general seems lower than before and much more stable (on master there are *a lot* of spikes compared to this branch).

This makes first run startup slower, although it makes it "more sane" because once the "Loading..." screen is gone you can interact with the MIDlet without any problem.
It shouldn't be too hard to optimize the implementation for the first run case (that is, the *appending data* case).

**Comment by marco-c** [comment]
> This makes first run startup slower, although it makes it "more sane" because once the "Loading..." screen is gone you can interact with the MIDlet without any problem.
It shouldn't be too hard to optimize the implementation for the first run case (that is, the appending data case).

I tried an optimization for the appending case, but it doesn't make a big difference.
I think startup isn't actually slower, it's just the FG MIDlet that is starting later in the process (probably because *open* doesn't unwind anymore).
I'll try to run the startup benchmark to validate this.

**Comment by marco-c** [comment]
Actually, the startup benchmark isn't valid here, because it's measuring the time it takes for the FG MIDlet to be shown.

**Comment by marco-c** [comment]
After an update, the difference in first run with master is considerably smaller.

**Comment by mykmelez** [comment]
I'm marking this request as incomplete and closing it, as the work here appears to have stalled.  Please reopen the request if you resume work on it!

**Pull request closed without merging**
